### ISSUE TITLE
SQL database

### ISSUE THREAD

**Issue by jmlasuncion** [lonelydev/DutchTreat#38]
Hi Eakan,
Any chance on getting a copy of the SQL database (.bak)?
I can not connect to "DutchConnectionString": "Server=tcp:egk-dutch-treat-db-server.database.windows.net,1433;Database=DutchTreatDb;Persist Security Info=False;User ID=egk-dutch-treat-admin;Password=D1u2T3c4H;MultipleActiveResultSets=True;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
Thanks,
Miguel

**Comment by lonelydev** [comment]
sorry Miguel. it is not meant to be up and running. 
It is just a tutorial project. Which is why the connection string is so exposed like this. 
The idea is that you will setup your own database with the seeder and other entity configuration in https://github.com/lonelydev/DutchTreat/tree/master/DutchTreat/Data
